import { createBrowserClient } from '@supabase/ssr'
import type { Database } from '@/lib/database.types'  // this file was generated by supabase gen types

export const supabase = createBrowserClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)